version: '2'
services:
  postgresql:
    image: postgres:9.4
    expose:
      - "5432"
  elasticsearch:
    image: elasticsearch:1.7
    expose:
      - "9200"
      - "9300"
  redis:
    image: redis:3.0
    expose:
      - "6379"
  bookbrainz-site:
    build:
      context: bookbrainz-site
      args:
        MB_OAUTH_CLIENT_ID: MBOAuthClientID
        MB_OAUTH_CLIENT_SECRET: MBOAuthClientSecret
        MB_OAUTH_CALLBACK_URL: http:\/\/localhost:9099\/cb
        SESSION_SECRET: SessionSecret
    volumes:
      - "./dumps:/dumps"
    links:
      - "postgresql:db"
